### ISSUE TITLE
Can factory.assoc return anything else other than model.id ?

### ISSUE THREAD

**Issue by jrcastillo** [aexmachina/factory-girl-bookshelf#5]
Hi, 
Currently im working with bookshelf models and trying to obtain an association that is not by an id. Here my example since this not clear enough.
```javascript
factory.define('foo', Foo, {
    username : factory.assoc('bar','id')
  });

factory.define('bar', Bar, {
    username        : () => casual.first_name + _.sample(['_','.']) + casual.last_name
  });
```
`Bar` does have an id but that does not work for my database reference, instead the username does work. Im trying to get that username doing:
```javascript
factory.define('foo', Foo, {
    username : factory.assoc('bar','username')
  });
```
and also tried:
```javascript
factory.define('foo', Foo, {
    username : factory.assoc('bar','attributes.username')
  });
```
Any help with this matter would be greatly appreciated
Thxs and sorry for the troubles

**Comment by aexmachina** [comment]
That's strange. That should just work. What is contained in the `username` attribute when you use `factory.assoc('bar', 'username')`.

What about if the `bar` factory doesn't use a function for the `username` attribute?

**Comment by jrcastillo** [comment]
So I tried the following 
```
factory.define('bar', Bar, {
    username        : 'exampleUsername'                 // assigning a simple string
  });

factory.define('foo', Foo, {
    username : factory.assoc('bar','attributes.username')
  });
```
these were the attribute values at `Foo.attributes`
```
{
  "username" : undefined
}
```
and just checking to see if everything was correct tries with 
```
factory.define('bar', Bar, {
    username        : 'exampleUsername'                 // assigning a simple string
  });

factory.define('foo', Foo, {
    username : factory.assoc('bar','attributes')
  });
```
and got the expected output
```
{
  "username": {
    "username": "exampleUsername",
    "created_at": "2016-05-27T14:14:28.953Z",
    "updated_at": "2016-05-27T14:14:28.953Z",
  },
}
```
which comes to thoughts: it seems that it can only access top-level attributes, since `username` field is not the `id`

**Comment by aexmachina** [comment]
It should just be 'username'. May be a bug, not sure why though -we have
tests.

**Comment by jrcastillo** [comment]
I had a look at the tests here and at factory-girl repository, I found where the assoc functionality had been tested but had a hard time finding out a place where non-top-level were tested.
I'm sorry to be such a trouble as you can see I'm just starting out in the world of github and kinda new to contributing

**Comment by aexmachina** [comment]
All good! It's the weekend here now. But I will have a look for you.

**Comment by aexmachina** [comment]
I added [a test for this](https://github.com/aexmachina/factory-girl/commit/25af7daca1e08426f9175c38da6418194c426d50#diff-38fc75c5b24d824849740aee309f754fR202) and it works as expected.

You should be able to do the following:

```js
factory.define('bar', Bar, {
  username: 'exampleUsername'
});
factory.define('foo', Foo, {
  username: factory.assoc('bar', 'username');
});
factory.build('foo', (err, o) => console.log(o.username)); // -> exampleUsername
```

**Comment by jrcastillo** [comment]
Sorry to keep bothering, there seems to be no solution to my problem, keep on crashing to the same bug. Don't know if this information helps but  I'm working with promises. I also re-downloaded factory-girl-bookshelf from npm to:
factory-girl-bookshelf is version 1.0.2
factory-girl is version 2.2.0 (dependency)

I'll give you a more complete example of what I'm doing.
Bookshelf model specification
```
var Bar = bookshelf.Model.extend({
  tableName: 'bar',
  idAttribute: 'id'
});

var Foo = bookshelf.Model.extend({
  tableName: 'foo',
  idAttribute: 'id'
});
```
Factory definition:
```
factory.define('bar', Bar, {
    email: 'traveler@example.com'
  });

  factory.define('foo', Foo, {
    domain: factory.assoc('bar', 'attributes.email')
  })
```
This is my test:
```
  it('should save properly with common information', (done) => {
    factory.build('foo')
      .then((foo) =>
        console.log(foo.attributes.domain))
      .then(done);
  });
```
Also tried: 
Factory definition:
```
factory.define('bar', Bar, {
    email: 'traveler@example.com'
  });

  factory.define('foo', Foo, {
    domain: factory.assoc('bar', 'email')
  })
```
This is my test result:
```
  it('should save properly with common information', (done) => {
    factory.build('foo')
      .then((foo) =>
        console.log(foo.attributes.domain))
      .then(done);
  });
```
for both tests Foo has this structure:
```
foo: {
   attributes: {
     domain: undefined
     },
   relations: {
   }
}
```
Might there exist the possibility that factory-girl version 2.2.0 does not support that operation ?
